//
// Created by dicta on 30.04.2024.
//

#ifndef CROSSDRESSSQL_FIELDCONSTRAINTS_H
#define CROSSDRESSSQL_FIELDCONSTRAINTS_H

enum class FieldConstraints {
    PRIMARY_KEY,
    FOREIGN_KEY,
    UNIQUE,
    NULLABLE
};

#endif //CROSSDRESSSQL_FIELDCONSTRAINTS_H
